scr_initenemy()
bigcheeseID = -4
pointerID = -4
destroyable = false
shakestun = false
hitspeed = 0
sit = true
blur_effect = 0
golfhit = [4, 6, 8]
arrowindex = 0
shootup = false
hitbuffer = 0
parryable = false
grav = 0.5
hsp = 0
vsp = 0
state = states.walk
stunned = 0
alarm[0] = 150
roaming = true
collectdrop = 5
flying = false
straightthrow = false
cigar = false
cigarcreate = false
stomped = false
shot = false
reset = false
flash = false
landspr = (global.mod_graceball ? spr_pizzaball_stun_grace : spr_pizzaball_stun)
idlespr = (global.mod_graceball ? spr_pizzaball_idle2_grace : spr_pizzaball_idle2)
fallspr = (global.mod_graceball ? spr_pizzaball_stun_grace : spr_pizzaball_stun)
stunfallspr = (global.mod_graceball ? spr_pizzaball_stun_grace : spr_pizzaball_stun)
walkspr = (global.mod_graceball ? spr_pizzaball_walk_grace : spr_pizzaball_walk)
turnspr = (global.mod_graceball ? spr_pizzaball_walk_grace : spr_pizzaball_walk)
recoveryspr = (global.mod_graceball ? spr_pizzaball_stun_grace : spr_pizzaball_stun)
grabbedspr = (global.mod_graceball ? spr_pizzaball_stun_grace : spr_pizzaball_stun)
scaredspr = (global.mod_graceball ? spr_pizzaball_stun_grace : spr_pizzaball_stun)
ragespr = spr_cheeseslime_rage
hp = 1
slapped = false
grounded = true
birdcreated = false
boundbox = false
spr_dead = (global.mod_graceball ? spr_pizzaball_stun_grace : spr_pizzaball_stun)
important = false
heavy = false
depth = 0
paletteselect = 0
spr_palette = palette_cheeseslime
grabbedby = 0
stuntouchbuffer = 0
scaredbuffer = 0
