scr_initenemy()
bigcheeseID = -4
pointerID = -4
destroyable = 0
shakestun = 0
hitspeed = 0
sit = 1
blur_effect = 0
golfhit = [4, 6, 8]
arrowindex = 0
shootup = 0
hitbuffer = 0
parryable = 0
grav = 0.5
hsp = 0
vsp = 0
state = (134 << 0)
stunned = 0
alarm[0] = 150
roaming = 1
collectdrop = 5
flying = 0
straightthrow = 0
cigar = 0
cigarcreate = 0
stomped = 0
shot = 0
reset = 0
flash = 0
landspr = (global.mod_graceball ? spr_pizzaball_stun_grace : spr_pizzaball_stun)
idlespr = (global.mod_graceball ? spr_pizzaball_idle2_grace : spr_pizzaball_idle2)
fallspr = (global.mod_graceball ? spr_pizzaball_stun_grace : spr_pizzaball_stun)
stunfallspr = (global.mod_graceball ? spr_pizzaball_stun_grace : spr_pizzaball_stun)
walkspr = (global.mod_graceball ? spr_pizzaball_walk_grace : spr_pizzaball_walk)
turnspr = (global.mod_graceball ? spr_pizzaball_walk_grace : spr_pizzaball_walk)
recoveryspr = (global.mod_graceball ? spr_pizzaball_stun_grace : spr_pizzaball_stun)
grabbedspr = (global.mod_graceball ? spr_pizzaball_stun_grace : spr_pizzaball_stun)
scaredspr = (global.mod_graceball ? spr_pizzaball_stun_grace : spr_pizzaball_stun)
ragespr = spr_cheeseslime_rage
hp = 1
slapped = 0
grounded = 1
birdcreated = 0
boundbox = 0
spr_dead = (global.mod_graceball ? spr_pizzaball_stun_grace : spr_pizzaball_stun)
important = 0
heavy = 0
depth = 0
paletteselect = 0
spr_palette = palette_cheeseslime
grabbedby = 0
stuntouchbuffer = 0
scaredbuffer = 0
