depth = 100
mask_index = spr_gerome_collected
scr_create_uparrowhitbox()
showtext = 0
alpha = 0
title = "Janice A.K.A. Fem-Gerome (Made by Benny):"
desc = (global.mod_femgerome == 1) ? "Enabled" : "Disabled"
sprite_index = (global.mod_femgerome == 1) ? spr_femgerome_collected : spr_gerome_collected
image_speed = 0.35
state = -1
sub_state = 0
timebuffer = 0
rat_mouth = -1
rat_stuffed = -1
cursor_spr = 740
cursor_state = 0
_image_index = 0
rat = 
{
    x: obj_screensizer.actual_width,
    y: obj_screensizer.actual_height,
    sprite_index: sprite_index,
    scale: 2
}
shroom = 
{
    state: states.normal,
    x: obj_screensizer.actual_width * 0.15,
    y: 100,
    spr_idle: spr_toppinshroom,
    spr_panic: spr_toppinshroom_panic,
    spr_pal: spr_shroompalette,
    sprite_index: spr_toppinshroom,
    image_index: 0,
    image_speed: 0.35,
    scale: 1,
    angle: 0
}
cheese = 
{
    state: states.normal,
    x: obj_screensizer.actual_width * 0.3,
    y: 100,
    spr_idle: spr_toppincheese,
    spr_panic: spr_toppincheese_panic,
    spr_pal: spr_cheesepalette,
    sprite_index: spr_toppincheese,
    image_index: 0,
    image_speed: 0.35,
    scale: 1,
    angle: 0
}
tomato = 
{
    state: states.normal,
    x: obj_screensizer.actual_width * 0.45,
    y: 100,
    spr_idle: spr_toppintomato,
    spr_panic: spr_toppintomato_panic,
    spr_pal: spr_tomatopalette,
    sprite_index: spr_toppintomato,
    image_index: 0,
    image_speed: 0.35,
    scale: 1,
    angle: 0
}
sausage = 
{
    state: states.normal,
    x: obj_screensizer.actual_width * 0.6,
    y: 100,
    spr_idle: spr_toppinsausage,
    spr_panic: spr_toppinsausage_panic,
    spr_pal: spr_sausagepalette,
    sprite_index: spr_toppinsausage,
    image_index: 0,
    image_speed: 0.35,
    scale: 1,
    angle: 0
}
pineapple = 
{
    state: states.normal,
    x: obj_screensizer.actual_width * 0.75,
    y: 100,
    spr_idle: spr_toppinpineapple,
    spr_panic: spr_toppinpineapple_panic,
    spr_pal: spr_papplepalette,
    sprite_index: spr_toppinpineapple,
    image_index: 0,
    image_speed: 0.35,
    scale: 1,
    angle: 0
}
toppin_array = [shroom, cheese, tomato, sausage, pineapple]

enum states
{
    normal,
    revolver,
    dynamite,
    boots,
    grabbed,
    tumble,
    finishingblow,
    ejected,
    transitioncutscene,
    fireass,
    firemouth,
    mort,
    mortjump,
    mortattack,
    morthook,
    hook,
    ghost,
    ghostpossess,
    titlescreen,
    hookshot,
    tacklecharge,
    cheeseball,
    cheeseballclimbwall,
    slap,
    cheesepep,
    cheesepepstick,
    cheesepepjump,
    cheesepepfling,
    cheesepeplaunch,
    cheesepepstickside,
    cheesepepstickup,
    rideweenie,
    motorcycle,
    boxxedpep,
    boxxedpepspin,
    boxxedpepjump,
    pistolaim,
    climbwall,
    knightpepslopes,
    portal,
    secondjump,
    chainsawbump,
    handstandjump,
    lungeattack,
    lungegrab,
    dashtumble,
    gottreasure,
    knightpep,
    knightpepattack,
    knightpepbump,
    meteorpep,
    bombpep,
    bombgrab,
    bombpepside,
    bombpepup,
    grabbing,
    chainsawpogo,
    shotgunjump,
    pogo,
    stunned,
    highjump,
    chainsaw,
    facestomp,
    unknown63,
    timesup,
    machroll,
    shotgun,
    shotguncrouch,
    shotguncrouchjump,
    shotgunshoot,
    shotgundash,
    shotgunfreefall,
    pistol,
    machfreefall,
    throwing,
    slam,
    superslam,
    skateboard,
    grind,
    grab,
    punch,
    backkick,
    uppunch,
    shoulder,
    backbreaker,
    graffiti,
    bossdefeat,
    pizzathrow,
    bossintro,
    gameover,
    keyget,
    tackle,
    jump,
    ladder,
    slipnslide,
    comingoutdoor,
    smirk,
    Sjump,
    victory,
    Sjumpprep,
    crouch,
    crouchjump,
    crouchslide,
    mach1,
    mach2,
    machslide,
    bump,
    hurt,
    freefall,
    hang,
    unknown110,
    freefallland,
    door,
    barrel,
    barreljump,
    barrelclimbwall,
    barrelslide,
    current,
    boulder,
    taxi,
    runonball,
    mach3,
    freefallprep,
    Sjumpland,
    faceplant,
    rage,
    idle,
    bounce,
    charge,
    pizzagoblinthrow,
    turn,
    unknown131,
    unknown132,
    rolling,
    walk,
    fall,
    land,
    hit,
    stun,
    unknown139,
    unknown140,
    chase,
    arenaspawn,
    arenaend,
    arenaintro,
    arenaround,
    actor,
    parry,
    golf,
    float,
    tube,
    unknown151,
    taxi2,
    shoulderbash,
    pummel,
    staggered,
    thrown,
    supershoulderbash,
    superattackstart,
    superattackcharge,
    superattack,
    shoulderturn,
    fistmatch,
    fistmatchend,
    groundpunchstart,
    slipbanan,
    millionpunch,
    skateboardturn,
    bombthrow,
    bombpogo,
    jetpackstart,
    jetpack,
    jetpackstart2,
    jetpackspin,
    mrstick_shield,
    mrstick_helicopterhat,
    mrstick_panicjump,
    mrstick_smokebombstart,
    mrstick_smokebombcrawl,
    mrstick_springshoes,
    mrstick_cardboard,
    mrstick_cardboardend,
    mrstick_mockery,
    bombdelete,
    rocket,
    rocketslide,
    gotoplayer,
    trickjump,
    dance,
    underground,
    ridecow,
    ratmount,
    ratmountjump,
    ratmountattack,
    ratmountspit,
    ratmountclimbwall,
    ratmounthurt,
    ratmountgroundpound,
    ratmountbounce,
    unknown199,
    ratmountballoon,
    ratmounttumble,
    ratmountgrind,
    ratmounttrickjump,
    ratmountskid,
    ratgrabbed,
    blockstance,
    balloon,
    debugstate,
    trashstart,
    trashjump,
    trashroll,
    stringfling,
    stringjump,
    stringfall,
    noisejetpack,
    spiderweb,
    monsteridle,
    monsterintro,
    monsterwalk,
    monsterchase,
    monsterinvestigate,
    monsterrun,
    flushidle,
    flushflip,
    animatronic,
    moustache,
    mouth,
    eyes,
    nose,
    ram,
    phase2transition,
    look,
    fishing,
    unknown234,
    bombrun,
    npcthrow,
    portraitthrow,
    enguarde,
    sexypicture,
    pullinglevel,
    eat,
    surprisebox,
    spinningrun,
    spin,
    spinningpunch,
    groundpunch,
    bigkick,
    slamhead,
    slamhead2,
    whitenoise,
    expression,
    playersuperattack,
    unknown253,
    jetpackjump,
    unknown255,
    unknown256,
    bee,
    beechase,
    ratmountpunch,
    ratmountcrouch,
    ratmountladder,
    supergrab,
    unknown263,
    attract,
    antigrav,
    secret,
    contemplate,
    mini,
    reloading,
    estampede,
    dropstart,
    drop,
    phase1hurt,
    duel,
    deformed,
    grabdash,
    grabthrow,
    wait,
    flamethrower,
    machinegun,
    bazooka,
    crate,
    noisecrusher,
    droptrap,
    noiseskateboard,
    noiseballooncrash,
    swinging,
    stomp,
    finale,
    backtohub,
    ghostcaught,
    spaceshuttle,
    animation,
    pizzaheadjump,
    fightball,
    secretportal,
    teleporter,
    pizzaheadKO,
    follow,
    unknown300,
    unknown301,
    unknown302,
    unknown303,
    unknown304,
    machcancelstart,
    machcancel
}
